services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - wp_content:/var/www/html/wp-content

  git-sync:
    image: alpine/git
    restart: "no"
    depends_on:
      - wordpress
    volumes:
      - wp_content:/wp-content
    entrypoint: >
      sh -c "
        git clone https://github.com/moronraul078-blip/WebFusion_Digital_S.L..git /tmp/repo &&
        cp /tmp/repo/index.php /var/www/html/index.php
      "

volumes:
  db_data:
  wp_content:
